/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-container": "#e7eeff",
        "primary": "#3525cd",
        "outline": "#777587",
        "surface-tint": "#4d44e3",
        "on-surface-variant": "#464555",
        "on-surface": "#111c2d",
        "on-tertiary-fixed": "#1a1b23",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ecf1ff",
        "on-background": "#111c2d",
        "secondary-fixed-dim": "#d2bbff",
        "error": "#ba1a1a",
        "on-primary-container": "#dad7ff",
        "secondary": "#712ae2",
        "secondary-container": "#8a4cfc",
        "on-tertiary-fixed-variant": "#46464f",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#25005a",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-fixed-dim": "#c7c5d1",
        "surface-bright": "#f9f9ff",
        "surface": "#f9f9ff",
        "on-primary-fixed": "#0f0069",
        "tertiary-fixed": "#e3e1ed",
        "inverse-surface": "#263143",
        "on-secondary-fixed-variant": "#5a00c6",
        "tertiary": "#474751",
        "surface-container-low": "#f0f3ff",
        "tertiary-container": "#5f5f69",
        "on-tertiary-container": "#dbdae5",
        "on-secondary-container": "#fffbff",
        "primary-container": "#4f46e5",
        "surface-container-highest": "#d8e3fb",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "surface-dim": "#cfdaf2",
        "error-container": "#ffdad6",
        "outline-variant": "#c7c4d8",
        "primary-fixed": "#e2dfff",
        "surface-variant": "#d8e3fb",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-high": "#dee8ff",
        "background": "#f9f9ff",
        "secondary-fixed": "#eaddff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "64px",
        "gutter": "24px",
        "xs": "8px",
        "base": "4px",
        "lg": "40px",
        "md": "24px",
        "sm": "16px",
        "container-max": "1280px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
